version: "3"
services:
  application:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 12
    command: sleep infinity
    env_file: .env.development
    ports:
      - 3003:3003
    volumes:
      - ..:/lps.dev.br
    links:
      - database

  database:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env.development
